# Generated by Django 5.2.7 on 2025-11-04 19:25

from django.db import migrations


class Migration(migrations.Migration):
    """
    Enable pgvector extension for PostgreSQL.

    This migration enables the pgvector extension which provides vector data types
    and similarity search operations. This extension is required for:
    - AI embeddings storage (Bloc 3: AI Content Pipeline)
    - Semantic search functionality (Bloc 5: Recommendation Engine)
    - Vector similarity operations (cosine similarity, L2 distance, etc.)

    Technical Requirements:
    - PostgreSQL 15+ with pgvector extension installed
    - Database user must have SUPERUSER privileges to create extensions
    - Extension must be enabled before any models with vector fields are created

    Security Notes:
    - SUPERUSER privilege is required ONLY for this initial migration
    - After extension is enabled, standard privileges are sufficient for vector operations
    - For production: Consider using a separate superuser for migrations only

    Idempotency:
    - Uses IF NOT EXISTS clause to safely re-run migration
    - Uses IF EXISTS clause for rollback safety
    - Safe to apply multiple times without errors

    Rollback:
    - Drops the vector extension and all vector columns/indexes
    - WARNING: Rollback will delete all vector data in the database
    - Only rollback if no models depend on vector fields

    Migration Verification:
    - After applying: Run verify_migrations management command
    - Test vector operations: SELECT '[1,2,3]'::vector;
    - Check extension: SELECT * FROM pg_extension WHERE extname = 'vector';
    """

    initial = True
    dependencies = []

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;',
        ),
    ]
